version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\hairyhenderson\gomplate

# Build host

environment:
  GOPATH: c:\gopath

init:
  - git config --global core.autocrlf input

# Build

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build github.com/hairyhenderson/gomplate
  - for /f "" %%G in ('go list github.com/hairyhenderson/gomplate/... ^| find /i /v "/vendor/"') do ( go test -v %%G & IF ERRORLEVEL == 1 EXIT 1)