version: 2
jobs:
  build:
    docker:
      - image: hairyhenderson/gomplate-ci-build:latest
    environment:
      - CIRCLE_TEST_REPORTS: /tmp/test-results
    working_directory: /go/src/github.com/hairyhenderson/gomplate
    steps:
      - checkout
      - run: make build
      - run:
          name: make test
          command: make test | go-junit-report > $CIRCLE_TEST_REPORTS/report.xml
      - run: make lint
      - run: make test-integration
      - store_artifacts:
          path: bin
          destination: binaries
      - store_test_results:
          path: /tmp/test-results
