[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/hairyhenderson/toml"
  branch = "support-map-interface-keys"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"
