baseURL = "/"
languageCode = "en-us"
title = "gomplate documentation"
theme = "hugo-theme-relearn"
googleAnalytics = "UA-82637990-3"

[params]
  alwaysopen = false
  editURL = "https://github.com/hairyhenderson/gomplate/edit/main/docs/content/"
  author = "hairyhenderson"
  description = "gomplate documentation"
  showVisitedLinks = false
  disableSearch = false
  disableSearchHiddenPages = false
  disableSeoHiddenPages = false
  disableTagHiddenPages = false
  disableAssetsBusting = false
  disableGeneratorVersion = false
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = false
  disableLandingPageButton = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = false
  disableToc = false
  disableMathJax = true
  disableMermaid = true
  disableSwagger = true
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariantAuto = ["gomplate-light", "gomplate-dark"]
  themeVariant = ["auto", "gomplate-light", "gomplate-dark"]
  titleSeparator = "-"
  collapsibleMenu = true
  additionalContentLanguage = [ "en" ]
  disableExplicitIndexURLs = true
  externalLinkTarget = "_blank"

[markup]
  [markup.highlight]
    guessSyntax = false
    noClasses = false

[outputs]
  home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[privacy]
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
