baseURL = "/"
languageCode = "en-us"
title = "gomplate documentation"

theme = "hugo-material-docs"

[params]
  author = "hairyhenderson"
  description = "gomplate documentation"
  copyright = "Released under the MIT license"
  provider = "GitHub"
  repo_url = "https://github.com/hairyhenderson/gomplate"
  googleAnalytics = "UA-82637990-1"

[params.palette]
  primary = "indigo"

[social]
  twitter = "hairyhenderson"
  github  = "hairyhenderson"
