name: Windows Build
on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    env:
      TMP: D:\tmp
      GOFLAGS: -mod=vendor
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@master
        with:
          path: ./src/github.com/${{ github.repository }}
      - run: make build
        env:
          GOPATH: ${{ runner.workspace }}
      - run: make test
        env:
          GOPATH: ${{ runner.workspace }}
      - run: make integration
        env:
          GOPATH: ${{ runner.workspace }}
